# CustomStats v2.0.0
# More detailed information on how to edit the configuration can be found on the wiki:
# https://7man7lmyt.github.io/CustomStats/



# New with v2.0.0: Placeholders

# The plugin supports PlaceholderAPI placeholders, as well as its own built in ones.
# Built in placeholders:
# %totalplayers% - How many unique players have joined the server
# %onlineplayers% - How many players are currently online.

stats:
  stat-command:
    - "&a-----------------------------------------------------"
    - "&6This server was created on July 30, 2022."
    - "&6The world is 12.34GB in size."
    - "&6%totalplayers% unique players have joined since."
    - "&a-----------------------------------------------------"

  # Customize the menu sent to Minecraft: Java Edition clients.
  stat-menu:
    # Format for adding more GUI items:
    # item(1-54):
    #  - (Item type)
    #  - "(display name)"
    # Max slots are limited to menu-size.
    # They are not required to be in order. Either set item type to air or don't set an item in the slot to leave blank.

    # Must be a multiple of 9.
    menu-size: 9

    title: "&3Server Stats Menu"
    items:
      3:
        - book
        - "&6This server was created on July 30, 2022."
      5:
        - grass_block
        - "&6The world is 12.34GB in size."
      7:
        - player_head
        - "&6%totalplayers% unique players have joined since."

  # Customize the form sent to Minecraft: Bedrock Edition clients. (Will only work if you have GeyserMC + Floodgate!)
  stat-form:
    # Format for adding more lines to the form:
    # content:
    #   - "&6This text is gold!"
    #   - "&lThis text is bold!"
    #   - "&0R&1a&2i&3n&4b&5o&6w &7C&8o&9l&ao&br&cs&d!&e!&f!

    title: "&3Server Stats Menu"
    content:
      - "&a--------------------------------"
      - "&6This server was created on July 30, 2022."
      - "&6The world is 12.34GB in size."
      - "&6%totalplayers% unique players have joined since."
      - "&a--------------------------------"
