# The configuration is simple.
statscommand:
  - '&a-----------------------------------------------------'
  - '&6This server was created on January 26, 2021.'
  - '&6The world is 12.34GB in size.'
  - '&6Over 1,234 players have joined since.'
  - '&a-----------------------------------------------------'
