# The configuration is simple.
#
# FORMAT FOR GUI ITEMS:
# item(1-9):
#  - (Item type)
#  - '(display name)'
# Max 9 slots, must be in order. Set item type to air to leave blank.
#
statscommand:
  - '&a-----------------------------------------------------'
  - '&6This server was created on January 26, 2021.'
  - '&6The world is 12.34GB in size.'
  - '&6Over 1,234 players have joined since.'
  - '&a-----------------------------------------------------'
statsgui:
  title:
    - '&3Stats GUI&0'
  item1:
    - dirt
    - '&3Example text'
  item2:
    - air
    - This is a nonphysical item!
