statcommand: '&a ----------------------------------------------------- &6This server
  was created on January 25, 2019.                    &6The world is 3.37GB in size.
  &6                                        Over 1,614 players have joined since.   &a-----------------------------------------------------'
