name: CustomStats
version: ${project.version}
main: me.stats.CustomStats.CustomStats
author: 7man7LMYT
website: https://discord.gg/Z5MyDwp
description: A plugin that adds /stats.
api-version: 1.12
commands:
  stats:
    description: Command to give information about the server.
    aliases: [statistics, serverinfo]
