name: CustomStats
version: ${project.version}
main: me.stats.CustomStats.CustomStats
author: 7man7LMYT
website: https://store.gamersclub.gq
description: A plugin that adds /stats.
api-version: 1.13
commands:
  stats:
    description: Command to give information about the server.
    aliases: [statistics, serverinfo]