name: CustomStats
version: 1.2.1
main: me.stats.CustomStats.CustomStats
author: 7man7LMYT
website: https://discord.gg/Z5MyDwp
description: An anarchy server oriented plugin that adds /stats.
api-version: 1.13
commands:
  stats:
    description: Command to give information about the server.
    aliases: [statistics]
